import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Pop The Pest",
  description: "Generated by create next app, by John, for demo purposes!",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
